#!/bin/bash

if [[ $IN_PRODUCTION != '' ]]
then
    export FLASK_ENV='production'   

else 
    export FLASK_ENV='development'
fi


export FLASK_APP='main'
export PYTHONPATH='.'

python3 db/create_tables.py