"""empty message

Revision ID: 6368b84d90ca
Revises: 
Create Date: 2024-09-15 23:22:55.192734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6368b84d90ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
